"""
YEDAN AGI - Research Module (Gemini Ultra Core)
Generating deep-dive intelligence reports using Specialized Gems.
"""
import os
import google.generativeai as genai
from datetime import datetime
from dotenv import load_dotenv
from agi_gems import GemRegistry

load_dotenv()

class AGIResearch:
    def __init__(self):
        self.api_key = os.getenv("GEMINI_API_KEY")
        if self.api_key:
            try:
                genai.configure(api_key=self.api_key)
                # Use 1.5 Pro for deep research
                self.model = genai.GenerativeModel('gemini-2.0-flash-001')
                self.gems = GemRegistry()
                print("[RESEARCH] Gemini Ultra Core: Online")
            except Exception as e:
                print(f"[RESEARCH] Init Failed: {e}")
                self.model = None
                self.gems = None
        else:
            self.model = None

    def generate_report(self, target_coin, visual_context=None, gem_name="YEDAN_PRIME"):
        """
        Generate a deep-dive report for a specific target using a specific Gem Persona.
        """
        if not self.model:
            return None

        # Get the specialized persona
        identity_prompt = self.gems.get_gem_prompt(gem_name)
        if not identity_prompt:
             identity_prompt = "Role: Financial Analyst"

        prompt = f"""
        {identity_prompt}
        
        ### TARGET ASSET
        **{target_coin}**
        
        ### CONTEXTUAL DATA
        Date: {datetime.now().strftime('%Y-%m-%d')}
        Market Context: {visual_context if visual_context else 'General Market Volatility'}
        
        ### ANALYSIS FRAMEWORK
        Analyze the target using your specialized expertise.
        
        ### OUTPUT FORMAT (STRICT)
        Generate a report in this exact structure.
        
        **TITLE**: [GEM: {gem_name}] {target_coin} // INTEL
        
        **I. EXECUTIVE SUMMARY (BLUF)**
        (Verdict from your persona's perspective)
        
        **II. DEEP DIVE**
        (Apply your specific directives to the analysis)
        
        **III. ACTION PLAN**
        (Concrete steps)
        
        ---
        *Generated by {gem_name} (Gemini Ultra Core)*
        """

        try:
            response = self.model.generate_content(prompt)
            return response.text
        except Exception as e:
            print(f"[RESEARCH] Generation error: {e}")
            return None

if __name__ == "__main__":
    # Test
    researcher = AGIResearch()
    print(researcher.generate_report("Midnight (NIGHT)", gem_name="YEDAN_PRIME"))
