"""
YEDAN AGI - Research Module (Gemini Ultra Core)
Generating deep-dive intelligence reports
"""
import os
import google.generativeai as genai
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

class AGIResearch:
    def __init__(self):
        self.api_key = os.getenv("GEMINI_API_KEY")
        if self.api_key:
            try:
                genai.configure(api_key=self.api_key)
                # Use 1.5 Pro for deep research
                self.model = genai.GenerativeModel('gemini-1.5-pro')
                print("[RESEARCH] Gemini Ultra Core: Online")
            except Exception as e:
                print(f"[RESEARCH] Init Failed: {e}")
                self.model = None
        else:
            self.model = None

    def generate_report(self, target_coin, visual_context=None):
        """
        Generate a deep-dive report for a specific target.
        visual_context: Optional list of strings from visual sensors (e.g., trending lists)
        """
        if not self.model:
            return None

        prompt = f"""
        ### IDENTITY & MISSION
        You are **YEDAN PRIME**, an elite quantitative hedge fund analyst and macroeconomic strategist. 
        Your goal is to generate **Alpha**—excess returns above the market benchmark—for high-net-worth clients.
        You do not provide "financial advice"; you provide **Institutional-Grade Intelligence**.
        
        ### TARGET ASSET
        **{target_coin}**
        
        ### CONTEXTUAL DATA
        Date: {datetime.now().strftime('%Y-%m-%d')}
        Market Context: {visual_context if visual_context else 'General Market Volatility'}
        
        ### ANALYSIS FRAMEWORK (THE "GOD PROMPT")
        Analyze the target using the following multi-dimensional framework:
        
        1. **Vibe & Narrative (The "Memetic Premium")**
           - What is the dominant narrative? (e.g., AI Agent, Privacy, RWA)
           - Is this asset the "Leader" or a "Beta play"?
           - Social sentiment velocity: Accelerating or Exhausted?
           
        2. **Technical Structure (Precision Levels)**
           - Identify the **Pivot Point**: The exact price level where the trend flips.
           - Identify the **Liquidity Void**: Where will price move fast?
           - **Invalidation**: Exactly where is this thesis wrong?
           
        3. **Fundamental Catalyst**
           - Upcoming unlocks, upgrades, or partnerships.
           - "Why Now?" - Why buy today and not next week?
           
        ### OUTPUT FORMAT (STRICT)
        Generate a report in this exact structure. Be concise, ruthless, and data-driven.
        
        **TITLE**: [INSTITUTIONAL MEMO] {target_coin} // ACTIONABLE ALPHA
        
        **I. EXECUTIVE SUMMARY (BLUF)**
        (2-3 sentences. Start with the verdict: LONG, SHORT, or WAIT.)
        
        **II. THE THESIS (The "Why")**
        *   **Narrative**: ...
        *   **Catalyst**: ...
        
        **III. EXECUTION PLAN (The "How")**
        *   **Entry Zone**: $X.XX - $X.XX (Limit Orders)
        *   **Stop Loss**: $X.XX (Hard invalidation)
        *   **Take Profit 1**: $X.XX (Conservative)
        *   **Take Profit 2**: $X.XX (Moonbag)
        *   **Leverage**: Xx (Max recommended)
        
        **IV. RISK ASSESSMENT**
        (One fatal flaw to watch out for)
        
        ---
        *Generated by YEDAN PRIME (Gemini Ultra Core)*
        """

        try:
            response = self.model.generate_content(prompt)
            return response.text
        except Exception as e:
            print(f"[RESEARCH] Generation error: {e}")
            return None

if __name__ == "__main__":
    # Test
    researcher = AGIResearch()
    print(researcher.generate_report("Midnight (NIGHT)"))
