"""
YEDAN REVENUE CORE - PRODUCT GENERATOR
Packaging Gemini Ultra Intel into Sellable PDF + Payment Link
"""
import time
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from agi_actions import AGIActions
import textwrap

# Intel from Gemini Ultra
INTEL_TITLE = "The Privacy Super-Cycle: NIGHT/USDT Alpha"
INTEL_BODY = """
YEDAN AGI REVENUE CORE // MARKET SCAN [COMPLETE]
DATE: DECEMBER 23, 2025
TARGETS: AAVE, PENGU (Pudgy Penguins), NIGHT (Midnight)

I. Market Diagnostics
1. Aave (AAVE) - [ACCUMULATION]: Technical recovery in progress. Institutional bidding identified in the $170-$180 zone. Target: $216.
2. Pudgy Penguins (PENGU) - [DISTRESSED]: Bearish breakdown. Failed marketing campaigns have led to retail traps. Verdict: AVOID or SHORT.
3. Midnight (NIGHT) - [VOLATILITY BREAKOUT]: Parabolic momentum driven by the Privacy sector rotation. This is the primary alpha asset.

II. High-Probability Trade Setup: NIGHT/USDT
* Direction: LONG
* Zone of Interest (Entry): $0.095 - $0.105
* Primary Target: $0.150 (+50%)
* Secondary Target: $0.220 (+110%)
* Invalidation (Stop Loss): Daily close below $0.082
* Leverage: 3x - 5x

CONFIDENTIAL - FOR PAID SUBSCRIBERS ONLY
Generated by Gemini 1.5 Pro (Ultra Core)
"""

SALES_TEASER = """<b>🚨 PRIVACY SUPER-CYCLE ALPHA DETECTED</b>

The Privacy Super-Cycle has arrived, and we've pinpointed the exact entry for the asset leading the charge (NIGHT).

We’ve mapped the whale accumulation zone that ensures you ride the massive leg up, not the wick.

Unlock the complete execution plan—entry, targets, and leverage strategy—inside the report. 

<b>[ACCESS FULL REPORT - $9.99]</b>
"""

def generate_product():
    actions = AGIActions()
    
    # 1. Create PDF
    pdf_filename = f"YEDAN_Alpha_{int(time.time())}.pdf"
    
    c = canvas.Canvas(pdf_filename, pagesize=letter)
    width, height = letter
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, INTEL_TITLE)
    c.line(50, height - 60, width - 50, height - 60)
    
    c.setFont("Helvetica", 12)
    y = height - 100
    for line in INTEL_BODY.split('\n'):
        # Wrap text
        wrapped = textwrap.wrap(line, width=80)
        for w_line in wrapped:
            c.drawString(50, y, w_line)
            y -= 15
    
    c.save()
    print(f"[PRODUCT] Generated PDF: {pdf_filename}")
    
    # 2. Generate Payment Link
    print("[PAYMENT] Generating PayPal Link...")
    payment_res = actions.create_payment("YEDAN Alpha: Privacy Super-Cycle", "9.99")
    
    if payment_res['success']:
        pay_url = payment_res['url']
        print(f"[PAYMENT] Link: {pay_url}")
        
        # 3. Broadcast to Telegram
        full_msg = f"{SALES_TEASER}\n<a href='{pay_url}'>👉 GET THE REPORT NOW</a>"
        tg_res = actions.telegram_send(full_msg)
        
        if tg_res['success']:
            print("[TELEGRAM] Broadcast Complete")
        else:
            print(f"[TELEGRAM] Failed: {tg_res['error']}")
    else:
        print(f"[PAYMENT] Failed: {payment_res['error']}")

if __name__ == "__main__":
    generate_product()
