"""
Site Architect
Demonstrates the capabilities of:
1. Storefront API (Reading public data for Headless builds)
2. Admin API (Writing assets/design to the current theme)
"""
import requests
import os
import json
from dotenv import load_dotenv
import base64

load_dotenv(dotenv_path=".env.reactor")

class SiteArchitect:
    def __init__(self):
        self.shop_url = os.getenv("SHOPIFY_STORE_URL", "").replace("https://", "")
        self.sf_token = os.getenv("SHOPIFY_STOREFRONT_OPEN_API")
        self.admin_token = os.getenv("SHOPIFY_ACCESS_TOKEN") or os.getenv("SHOPIFY_ADMIN_TOKEN")
        
    def test_storefront_api(self):
        """
        Use Storefront API to fetch products. 
        This is what we'd use if we were building a 'Webnode' style custom site.
        """
        print("\n[1/2] Testing Storefront API (Headless Capability)...")
        if not self.sf_token:
            print("   [Error] No Storefront Token.")
            return

        url = f"https://{self.shop_url}/api/2024-01/graphql.json"
        headers = {
            "X-Shopify-Storefront-Access-Token": self.sf_token,
            "Content-Type": "application/json"
        }
        
        query = """
        {
          products(first: 3) {
            edges {
              node {
                title
                description
                priceRange {
                  minVariantPrice {
                    amount
                    currencyCode
                  }
                }
              }
            }
          }
        }
        """
        
        try:
            r = requests.post(url, json={"query": query}, headers=headers)
            if r.status_code == 200:
                data = r.json()
                products = data.get('data', {}).get('products', {}).get('edges', [])
                print(f"   [Success] Storefront API Read {len(products)} products.")
                for p in products:
                    print(f"   - {p['node']['title']} ({p['node']['priceRange']['minVariantPrice']['amount']} {p['node']['priceRange']['minVariantPrice']['currencyCode']})")
                print("   [Conclusion] We CAN build a custom headless site (React/Vue) if you want.")
            else:
                print(f"   [Error] API Status: {r.status_code} {r.text}")
        except Exception as e:
            print(f"   [Error] Failed: {e}")

    def test_theme_injection(self):
        """
        Use Admin API to modify the current Theme.
        This is used for 'Decorating' the current Spotify/Shopify site (Penpot workflow).
        """
        print("\n[2/2] Testing Admin API (Design/Theme Injection)...")
        if not self.admin_token:
            print("   [Error] No Admin Token.")
            return

        headers = {"X-Shopify-Access-Token": self.admin_token}
        
        # 1. Get Main Theme
        try:
            r = requests.get(f"https://{self.shop_url}/admin/api/2024-01/themes.json", headers=headers)
            themes = r.json().get('themes', [])
            main_theme = next((t for t in themes if t['role'] == 'main'), None)
            
            if not main_theme:
                print("   [Error] No main theme found.")
                return
                
            print(f"   [Success] Found Main Theme: '{main_theme['name']}' (ID: {main_theme['id']})")
            
            # 2. Simulate uploading a 'Penpot' generated banner
            # Creating a simple text file asset as a proof of concept
            asset_key = "assets/yedan_architect_proof.txt"
            asset_value = "This file was auto-generated by YEDAN Site Architect. We can upload images here."
            
            payload = {
                "asset": {
                    "key": asset_key,
                    "value": asset_value
                }
            }
            
            put_url = f"https://{self.shop_url}/admin/api/2024-01/themes/{main_theme['id']}/assets.json"
            r = requests.put(put_url, json=payload, headers=headers)
            
            if r.status_code in [200, 201]:
                print(f"   [Success] Injected '{asset_key}' into theme.")
                print("   [Conclusion] We CAN automate design updates (Penpot -> Shopify Banner).")
            else:
                print(f"   [Error] Asset upload failed: {r.status_code}")
                
        except Exception as e:
            print(f"   [Error] Failed: {e}")

if __name__ == "__main__":
    print("=== YEDAN Site Architect ===")
    arch = SiteArchitect()
    arch.test_storefront_api()
    arch.test_theme_injection()
